[package]
name = "forma"
version = "0.1.0"
authors = ["Max Countryman <maxc@me.com>"]
edition = "2018"
description = "An opinionated SQL formatter."
license = "MIT"

[dependencies]
formation = { path = "../formation" }
structopt = "0.3.14"
