[package]
name = "formation"
version = "0.1.0"
authors = ["Max Countryman <maxc@me.com>"]
edition = "2018"
description = "A deflightful SQL formatter."
license = "MIT"

[dependencies]
sqlparser = "0.5.0"
pretty = "0.10.0"
